#!/usr/bin/env bash
source /home/xap/docker/env.sh

#first arg is branch, second arg is build number
BRANCH=$1
BUILD=$2

echo "start publishing - date `date`"
echo "Arguments are BRANCH=${BRANCH}, BUILD=${BUILD}."

PARENT_BUILDS_DIR_NAME=builds
PUBLISH_BUILDS_FOLDER=${WEB_FOLDER}/${PARENT_BUILDS_DIR_NAME}
WEB_URI_BUILDS_FOLDER=${BASE_WEB_URI}/${PARENT_BUILDS_DIR_NAME}

UPDATED_JAR_PATH=/home/xap/testing-grid/bin
echo "PUBLISH_BUILDS_FOLDER=${PUBLISH_BUILDS_FOLDER}"
echo "WEB_URI_BUILDS_FOLDER=${WEB_URI_BUILDS_FOLDER}"

LOCAL_PATH_TO_BUILD=${PUBLISH_BUILDS_FOLDER}/${BRANCH}/${BUILD}
WEB_PATH_TO_BUILD=${WEB_URI_BUILDS_FOLDER}/${BRANCH}/${BUILD}

echo "LOCAL_PATH_TO_BUILD=${LOCAL_PATH_TO_BUILD}"
echo "WEB_PATH_TO_BUILD=${WEB_PATH_TO_BUILD}"

GS_BUILD_ZIP=$(find ${LOCAL_PATH_TO_BUILD} -name '*giga*.zip')
GS_BUILD_ZIP=`basename ${GS_BUILD_ZIP}`

printf "GS_BUILD_ZIP=${GS_BUILD_ZIP}\n\n" 

export NEWMAN_BUILD_BRANCH=${BRANCH}
export NEWMAN_BUILD_NUMBER=${BUILD}

export NEWMAN_BUILD_TESTS_METADATA=${WEB_PATH_TO_BUILD}/tgrid-tests-metadata.json,${WEB_PATH_TO_BUILD}/sgtest-tests.json,${WEB_PATH_TO_BUILD}/http-session-tests.json,${WEB_PATH_TO_BUILD}/mongodb-tests.json
export NEWMAN_BUILD_SHAS_FILE=${WEB_PATH_TO_BUILD}/metadata.txt
export NEWMAN_BUILD_RESOURCES=${WEB_PATH_TO_BUILD}/testsuite-1.5.zip,${WEB_PATH_TO_BUILD}/${GS_BUILD_ZIP},${WEB_PATH_TO_BUILD}/newman-artifacts.zip,${WEB_PATH_TO_BUILD}/SGTest-sources.zip

echo "NEWMAN_BUILD_BRANCH=${NEWMAN_BUILD_BRANCH}"
echo "NEWMAN_BUILD_NUMBER=${NEWMAN_BUILD_NUMBER}"
echo "NEWMAN_HOST=${NEWMAN_HOST}"
echo "NEWMAN_USER_NAME=${NEWMAN_USER_NAME}"
echo "NEWMAN_BUILD_TESTS_METADATA=${NEWMAN_BUILD_TESTS_METADATA}"
echo "NEWMAN_BUILD_SHAS_FILE=${NEWMAN_BUILD_SHAS_FILE}"
echo "NEWMAN_BUILD_RESOURCES=${NEWMAN_BUILD_RESOURCES}"

java -cp ${UPDATED_JAR_PATH}/newman-submitter-1.0.jar com.gigaspaces.newman.NewmanBuildSubmitter

echo "finish submitting"
echo ""