#!/bin/bash
source env.sh
docker rm -f xap
docker run -it -e "TGRID_BUILD_NUMBER=${TGRID_BUILD_NUMBER}" -e "TGRID_GS_PRODUCT_VERSION=${TGRID_GS_PRODUCT_VERSION}" -e "TGRID_S3_PUBLISH_FOLDER=${TGRID_S3_PUBLISH_FOLDER}" -e "TGRID_MILESTONE=${TGRID_MILESTONE}" -e "TGRID_SUITE_CUSTOM_EXCLUDE=${TGRID_SUITE_CUSTOM_EXCLUDE}" -e "TGRID_SUITE_CUSTOM_INCLUDE=${TGRID_SUITE_CUSTOM_INCLUDE}" -e "TGRID_SUITE_CUSTOM_JVMARGS=${TGRID_SUITE_CUSTOM_JVMARGS}" -e "TGRID_SUITE_CUSTOM_SYSPROPS=${TGRID_SUITE_CUSTOM_SYSPROPS}" -e "TGRID_QA_SUITE_VERSION=${TGRID_QA_SUITE_VERSION}" -e "TGRID_TARGET_JVM=${TGRID_TARGET_JVM}" -e "GIT_BRANCH=${GIT_BRANCH}" -e "FORCE=${FORCE}" -v ${SOURCES_DIR}:/sources -v ${BUILD_DOCKER_HOME}/.ssh:/root/foo -v ${BUILD_DOCKER_HOME}/counter.sh:/root/counter.sh -v ${BUILD_DOCKER_HOME}/counter.tmp:/root/counter.tmp -v ${BUILD_DOCKER_HOME}/branch_list.txt:/root/branch_list.txt --name xap builder/xap bash

